/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
    './app.vue',
    './error.vue',
    './node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'selector',
  theme: {
    screens: {
      mobile: '768px',
      tablet: '1024px',
      desktop: '1216px',
      widescreen: '1408px',
    },
    fontFamily: {
      sans: [
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      mono: ['Inconsolata', 'Hack', 'SF Mono', 'Roboto Mono', 'Source Code Pro', 'Ubuntu Mono', 'monospace'],
    },
    extend: {
      colors: {
        secondary: {
          DEFAULT: 'var(--p-secondary-500)',
          50: 'var(--p-secondary-50)',
          100: 'var(--p-secondary-100)',
          200: 'var(--p-secondary-200)',
          300: 'var(--p-secondary-300)',
          400: 'var(--p-secondary-400)',
          500: 'var(--p-secondary-500)',
          600: 'var(--p-secondary-600)',
          700: 'var(--p-secondary-700)',
          800: 'var(--p-secondary-800)',
          900: 'var(--p-secondary-900)',
          950: 'var(--p-secondary-950)',
        },
        default: 'var(--p-text-color)',
      },
      boxShadow: {
        card: '0 1px 4px 0 rgba(0,0,0,0.2)',
      },
      backgroundColor: {
        body: 'var(--body-background-color)',
        hover: 'var(--p-surface-100)',
      },
      backgroundImage: {
        'laurentf-sajama-800': `image-set(url('~/assets/img/backgrounds/laurentf-sajama-800w.webp') type('image/webp'), url('~/assets/img/backgrounds/laurentf-sajama-800w.jpg') type('image/jpeg'))`,
        'laurentf-sajama-1024': `image-set(url('~/assets/img/backgrounds/laurentf-sajama-1024w.webp') type('image/webp'), url('~/assets/img/backgrounds/laurentf-sajama-1024w.jpg') type('image/jpeg'))`,
        'laurentf-sajama-1200': `image-set(url('~/assets/img/backgrounds/laurentf-sajama-1200w.webp') type('image/webp'), url('~/assets/img/backgrounds/laurentf-sajama-1200w.jpg') type('image/jpeg'))`,
        'alexbuisse-greenland-800': `image-set(url('~/assets/img/backgrounds/alexbuisse-greenland-800w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexbuisse-greenland-800w.jpg') type('image/jpeg'))`,
        'alexbuisse-greenland-1024': `image-set(url('~/assets/img/backgrounds/alexbuisse-greenland-1024w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexbuisse-greenland-1024w.jpg') type('image/jpeg'))`,
        'alexbuisse-greenland-1200': `image-set(url('~/assets/img/backgrounds/alexbuisse-greenland-1200w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexbuisse-greenland-1200w.jpg') type('image/jpeg'))`,
        'cermygian-crevasse-800': `image-set(url('~/assets/img/backgrounds/cermygian-crevasse-800w.webp') type('image/webp'), url('~/assets/img/backgrounds/cermygian-crevasse-800w.jpg') type('image/jpeg'))`,
        'cermygian-crevasse-1024': `image-set(url('~/assets/img/backgrounds/cermygian-crevasse-1024w.webp') type('image/webp'), url('~/assets/img/backgrounds/cermygian-crevasse-1024w.jpg') type('image/jpeg'))`,
        'cermygian-crevasse-1200': `image-set(url('~/assets/img/backgrounds/cermygian-crevasse-1200w.webp') type('image/webp'), url('~/assets/img/backgrounds/cermygian-crevasse-1200w.jpg') type('image/jpeg'))`,
        'alexsaunier-monch-800': `image-set(url('~/assets/img/backgrounds/alexsaunier-monch-800w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexsaunier-monch-800w.jpg') type('image/jpeg'))`,
        'alexsaunier-monch-1024': `image-set(url('~/assets/img/backgrounds/alexsaunier-monch-1024w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexsaunier-monch-1024w.jpg') type('image/jpeg'))`,
        'alexsaunier-monch-1500': `image-set(url('~/assets/img/backgrounds/alexsaunier-monch-1500w.webp') type('image/webp'), url('~/assets/img/backgrounds/alexsaunier-monch-1500w.jpg') type('image/jpeg'))`,
      },
    },
  },
  plugins: [require('tailwindcss-primeui')],
};
